all:
	cd object_detection; cmake .; make
	cd object_hole_filling; cmake .; make
	cd object_segmentation; cmake .; make
	cd texture; cmake .; make

clean:
	cd object_detection; make clean
	cd object_hole_filling; make clean
	cd object_segmentation; make clean
	cd texture; make clean
