#./generate_thumbnail_cli ~/Box_Sync/research/structured_indoor_modeling/data/equal-sky-0649
./generate_thumbnail_cli ~/Box_Sync/research/structured_indoor_modeling/data/lumber-cashew-1997
#./generate_thumbnail_cli ~/Box_Sync/research/structured_indoor_modeling/data/new-breeze-6946
./generate_thumbnail_cli ~/Box_Sync/research/structured_indoor_modeling/data/red-lion-9567
./generate_thumbnail_cli ~/Box_Sync/research/structured_indoor_modeling/data/salmon-palace-2313
#./generate_texture_cli ~/Box_Sync/research/structured_indoor_modeling/data/equal-sky-0649
./generate_texture_cli ~/Box_Sync/research/structured_indoor_modeling/data/lumber-cashew-1997
#./generate_texture_cli ~/Box_Sync/research/structured_indoor_modeling/data/new-breeze-6946
./generate_texture_cli ~/Box_Sync/research/structured_indoor_modeling/data/red-lion-9567
./generate_texture_cli ~/Box_Sync/research/structured_indoor_modeling/data/salmon-palace-2313
